<?php

/**
 * Implements hook_requirements().
 *
 * So that oven is not enabled in production.
 *
 * @param $phase
 *
 * @return array
 */
function entityspice_oven_requirements($phase) {
  return $phase === 'runtime'
    ? [
      'title' => 'Entityspice Oven in production',
      'description' => 'Entityspice Oven must not be enabled in production',
      'severity' => REQUIREMENT_WARNING,
    ]
    : [];
}
